# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rsqlx_wrappers", use_symbols = TRUE, package_name = "rsqlx")

#' @usage NULL
#' @useDynLib rsqlx, .registration = TRUE
NULL

r_read_table <- function(conn_str, table) .Call(wrap__r_read_table, conn_str, table)

hello_world <- function() .Call(wrap__hello_world)


# nolint end
